DROP DATABASE IF EXISTS BUCKET;
CREATE DATABASE BUCKET;
USE BUCKET;


CREATE TABLE GRUPO_USR (
GRP_COD TINYINT PRIMARY KEY AUTO_INCREMENT,
GRP_DESC VARCHAR(20),
PERMS_COD TINYINT
);

CREATE TABLE PERMISSAO (
PERMS_COD TINYINT PRIMARY KEY,
PERMS_DESC VARCHAR(40 )
);

CREATE TABLE USUARIO (
USR_COD INT PRIMARY KEY,
USR_NOME VARCHAR( 200),
USR_EMAIL VARCHAR( 200),
USR_CELULAR VARCHAR( 15),
USR_SENHA VARCHAR(15),
USR_LOGIN VARCHAR(15)
);

CREATE TABLE RECEITA (
RCEI_COD INT PRIMARY KEY,
RCEI_DESCRI VARCHAR( 200),
RCEI_DTCADASTR DATETIME,
RCEI_DTRECEB DATETIME,
RCEI_DTVENC DATETIME,
RECEI_VLRRECEBIDO DOUBLE(10,2),
RCEI_VLRTITULO DOUBLE(10,2),
RCEI_JUROSAODIA CHAR(3),
RCEI_FORPG VARCHAR( 15),
RCEI_NPARCELAS TINYINT,
SETR_COD INT
);

CREATE TABLE DESPESA (
DESP_COD INT PRIMARY KEY,
DESP_DESCRI VARCHAR( 200),
DESP_DTCADASTR DATETIME,
DESP_DTVENC DATETIME,
DESP_DTPAG DATETIME,
DESP_VLRPAGO DOUBLE(10,2),
DESP_VALRTITULO DOUBLE(10,2),
DESP_JUROSAODIA CHAR(3),
DESP_NPARCELAS TINYINT,
DESP_FORMPG VARCHAR( 15),

SETR_COD INT
);

CREATE TABLE UF (
UF_COD INT PRIMARY KEY AUTO_INCREMENT,
UF_SIGLA CHAR(2),
UF_ESTADO VARCHAR(60)
);

CREATE TABLE PJ (
PJ_COD INT PRIMARY KEY,
PJ_CNPJ VARCHAR( 15),
PJ_RAZAO_SOCIAL VARCHAR( 200),
PJ_NOME_FANTASIA VARCHAR( 200),
PJ_NOME_REPRESN VARCHAR( 200),
PJ_TELEFONE VARCHAR( 15),
PJ_TEL_REPRESN VARCHAR( 15)
);

CREATE TABLE PF (
PF_COD INT PRIMARY KEY,
PF_SEXO CHAR(4),
PF_CPF VARCHAR( 11),
PF_CEL VARCHAR(15),
PF_NOME VARCHAR(200),
PF_EMAIL VARCHAR(200 ),
PF_TEL VARCHAR( 14)
);

CREATE TABLE PJ_RECEITA (
PJ_RECEITA_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
PJ_COD INT,
RCEI_COD INT,
USUARIO_COD INT,
FOREIGN KEY(PJ_COD) REFERENCES PJ (PJ_COD),
FOREIGN KEY(RCEI_COD) REFERENCES RECEITA (RCEI_COD),
FOREIGN KEY(USUARIO_COD) REFERENCES USUARIO (USR_COD)
);

CREATE TABLE PF_RECEITA (
PF_RECEITA_COD INT PRIMARY KEY AUTO_INCREMENT,
PF_COD INT,
RCEI_COD INT,
USUARIO_COD INT,
FOREIGN KEY(PF_COD) REFERENCES PF (PF_COD),
FOREIGN KEY(RCEI_COD) REFERENCES RECEITA (RCEI_COD),
FOREIGN KEY(USUARIO_COD) REFERENCES USUARIO (USR_COD)
);

CREATE TABLE USUARIO_GRUPO (
USUARIO_GRUPO TINYINT PRIMARY KEY AUTO_INCREMENT,
GRP_COD TINYINT,
USR_COD INT,
FOREIGN KEY(GRP_COD) REFERENCES GRUPO_USR (GRP_COD),
FOREIGN KEY(USR_COD) REFERENCES USUARIO (USR_COD)
);

CREATE TABLE PF_END (
PF_END_COD INT PRIMARY KEY AUTO_INCREMENT,
END_COD INT,
PF_COD INT,
FOREIGN KEY(PF_COD) REFERENCES PF (PF_COD)
);

CREATE TABLE PJ_DESPESA (
PJ_DESPESA_COD INT PRIMARY KEY AUTO_INCREMENT,
PJ_COD INT,
DESP_COD INT,
USUARIO_COD INT,
FOREIGN KEY(PJ_COD) REFERENCES PJ (PJ_COD),
FOREIGN KEY(DESP_COD) REFERENCES DESPESA (DESP_COD),
FOREIGN KEY(USUARIO_COD) REFERENCES USUARIO (USR_COD)
);

CREATE TABLE PJ_END (
PJ_END_COD INT PRIMARY KEY AUTO_INCREMENT,
END_COD INT,
PJ_COD INT,
FOREIGN KEY(PJ_COD) REFERENCES PJ (PJ_COD)
);

CREATE TABLE SETOR (
SETR_COD INT PRIMARY KEY AUTO_INCREMENT,
SETR_NOME VARCHAR(50),
SETR_TIPO VARCHAR(50)
);

CREATE TABLE ENDERECO (
END_COD INT PRIMARY KEY,
END_NOME VARCHAR(250),
END_BAIRRO VARCHAR(250),
END_NUM CHAR(8),
END_CEP CHAR(8),
END_COMP VARCHAR(250),
UF_COD INT,
FOREIGN KEY(UF_COD) REFERENCES UF (UF_COD)
);

CREATE TABLE PF_DESPESA (
PF_DESP_COD INT PRIMARY KEY AUTO_INCREMENT,
PF_COD INT,
DESP_COD INT,
USUARIO_COD INT,
FOREIGN KEY(PF_COD) REFERENCES PF (PF_COD),
FOREIGN KEY(DESP_COD) REFERENCES DESPESA (DESP_COD),
FOREIGN KEY(USUARIO_COD) REFERENCES USUARIO (USR_COD)
);

ALTER TABLE GRUPO_USR ADD FOREIGN KEY(PERMS_COD) REFERENCES PERMISSAO (PERMS_COD);
ALTER TABLE RECEITA ADD FOREIGN KEY(SETR_COD) REFERENCES SETOR (SETR_COD);
ALTER TABLE DESPESA ADD FOREIGN KEY(SETR_COD) REFERENCES SETOR (SETR_COD);
ALTER TABLE PF_END ADD FOREIGN KEY(END_COD) REFERENCES ENDERECO (END_COD);
ALTER TABLE PJ_END ADD FOREIGN KEY(END_COD) REFERENCES ENDERECO (END_COD);



-- ------------------------- INSERTS INICIAIS -- -----------------------------------


-- ------------------------- INSERTS INICIAIS -- -----------------------------------


INSERT INTO UF VALUES (0,"SP", "São Paulo"), (0, "AC", "Acre"), (0, "AL", "Alagoas"), (0, "AP", "Amapá"), (0, "AM", "Amazonas"), (0, "BA", "Bahia"),
(0, "CE", "Ceará"), (0, "DF	", "Distrito Federal"), (0, "ES", "Espírito Santo"), (0, "GO", "Goiânia"), (0, "MA", "Maranhão"), (0, "MT", "Mato Grosso"), (0, "MS", "Mato Grosso do Sul"), (0, "MG", "Minas Gerais"), (0, "PA", "Pará"),
(0, "PB	", "Paraíba"), (0, "PR", "Paraná"), (0, "PE", "Pernambunco"), (0, "PI", "Piauí"), (0, "RJ", "Rio de Janeiro"), (0, "RN", "Rio Grande do Norte"), (0, "RS", "Rio Grande do Sul"), (0, "RO", "Rondônia"), (0, "RR", "Roraima"), 
(0, "SC", "Santa Catarina"), (0, "SE", "Sergipe"), (0, "TO", "Tocantins");


SELECT * FROM UF